// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlIsqDqL_eLLRNsj2yTZpaMib1czfoVCU',
    appId: '1:220256040413:android:8e9944c1341f86e496f234',
    messagingSenderId: '220256040413',
    projectId: 'paylyht',
    databaseURL: 'https://paylyht-default-rtdb.firebaseio.com',
    storageBucket: 'paylyht.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFldrPpaNwPzGj5s6UWB-cF_p1MtJi49k',
    appId: '1:220256040413:ios:284c8231607c3d9c96f234',
    messagingSenderId: '220256040413',
    projectId: 'paylyht',
    databaseURL: 'https://paylyht-default-rtdb.firebaseio.com',
    storageBucket: 'paylyht.firebasestorage.app',
    androidClientId:
        '220256040413-e3sgdv9rd5i2n855cbhli8i5ttc0jqp4.apps.googleusercontent.com',
    iosClientId:
        '220256040413-o5ennq83uatimrtage5d7md8uonsofvk.apps.googleusercontent.com',
    iosBundleId: 'ht.payly.tev',
  );
}
